### ISSUE TITLE
Incompatible with Linux screen

### ISSUE THREAD

**Issue by elCapitanoh** [jsappme/node-binance-trader#9]
For whatever reason, this program does not work when attempting to run it with the Linux command screen. I am running this command so I can idle the program on my server without needing the terminal open (and in case of connection drops).

Example: 'screen node index.js' leads to the program hanging at the NBT logo, the first question regarding order pair does not come up as expected.

Is there any way I can hardcode my config so I could use nohup instead? Thanks.

**Comment by elCapitanoh** [comment]
As a side question, does setting stop loss percent to 0 disable the feature? Let's say I just wanted profit hunting mode and wanted the bot to disregard drops in price, only sell at profit target and then create another order.

**Comment by jsappme** [comment]
Hi,

I am not sure why it does not properly with screen. I will do some tests.
Yes, you will have to customize the code a bit in order to run it automatically on your server.

No, you can't input a stop loss percent lower than 0.11 (it means a max loss of %0.11), because below this min. value, the bot has too much probabilities to sell just after buying the pair.

I will close this issue for now because it's not a real issue with the core functionality of the bot but I keep in mind that having an autonomous version will be a serious need in the near future when the core trading executions have been cleared of any issues.
